# -*- coding: utf-8 -*-
"""BISINDO0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEWb66H61j55hA9I1SptO_zJjgEe3nXO

# Machine Learning Project by Rizka Alfadilla: [BISINDO0]

## Packages/Library
"""

# Tunggu hingga semua library terinstall baru restart session

!pip install tensorflowjs

# Menonaktifkan warning yang mungkin muncul
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Library Umum
import os
import sys
import shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

# Machine Learning & Model Inference
import tensorflow as tf
import joblib
import tensorflowjs

# Pelatihan dan evaluasi
import seaborn as sns
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Mencetak versi Library yang sedang digunakan
print(f'Python Version: {sys.version.split()[0]}')
print(f'Pandas Version: {pd.__version__}')
print(f'Numpy Version: {np.__version__}')
print(f'Scikit Learn Version: {sklearn.__version__}')
print(f'Tensorflow Version: {tf.__version__}')
print(f'TensorFlow.js Version: {tensorflowjs.__version__}')

"""## Data Preparation

### Data Loading
"""

df = pd.read_csv("bisindo_landmarks_scaled.csv")

df.head(10)

# Plot distribusi gambar di setiap kelas
Label = df['label']
plt.figure(figsize = (6,6))
sns.set_style("darkgrid")
plot_data = sns.countplot(Label)

df['label'].value_counts()

"""### Data Preprocessing

#### Split Dataset
"""

def split_train_test(csv_filename, train_file, test_file, train_size=0.8):

    # Load dataset
    df = pd.read_csv(csv_filename)

    # Pisahkan fitur dan label
    if 'label' not in df.columns:
        raise ValueError("CSV harus memiliki kolom 'label'")

    X = df.drop(columns=['label'])
    y = df['label']

    # Split dataset
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        train_size=train_size,
        stratify=y,
        random_state=42
    )

    # Buat DataFrame untuk train dan test
    train_df = pd.concat([y_train.reset_index(drop=True), X_train.reset_index(drop=True)], axis=1)
    test_df = pd.concat([y_test.reset_index(drop=True), X_test.reset_index(drop=True)], axis=1)

    # Simpan ke CSV
    train_df.to_csv(train_file, index=False)
    test_df.to_csv(test_file, index=False)

    print(f"Dataset berhasil dibagi:")
    print(f"  Train Set: {train_df.shape[0]} sampel, {train_df.shape[1]} kolom")
    print(f"  Test Set:  {test_df.shape[0]} sampel, {test_df.shape[1]} kolom")

    return train_df, test_df

train_df, test_df = split_train_test(
    "bisindo_landmarks_scaled.csv",
    'train.csv',
    'test.csv',
    train_size=0.8
)

"""## Modelling"""

# Parameter
input_dim = 126  # 2 tangan x 21 landmark x 3 koordinat
epochs = 100
batch_size = 32

checkpoint_dir = './checkpoints'
saved_model_mlp_dir = './saved_models_mlp'

# Pastikan folder ada
os.makedirs(checkpoint_dir, exist_ok=True)
os.makedirs(saved_model_mlp_dir, exist_ok=True)

##### Function: Load Train and Test Dataset

def load_dataset(train_file, test_file):
    train_df = pd.read_csv(train_file)
    test_df = pd.read_csv(test_file)

    # Pastikan kolom label tersedia
    if 'label' not in train_df.columns or 'label' not in test_df.columns:
        raise ValueError("File train dan test harus memiliki kolom 'label'.")

    # Kolom yang bukan fitur
    non_feature_columns = ['label', 'path', 'file_name']

    drop_train = [
        col for col in non_feature_columns
        if col in train_df.columns
    ]

    drop_test = [
        col for col in non_feature_columns
        if col in test_df.columns
    ]

    # Pisahkan fitur dan label
    X_train = train_df.drop(columns=drop_train).values
    y_train = train_df['label'].values

    X_test = test_df.drop(columns=drop_test).values
    y_test = test_df['label'].values

    # Encode labels
    label_encoder = LabelEncoder()
    y_train = label_encoder.fit_transform(y_train)
    y_test = label_encoder.transform(y_test)

    return X_train, y_train, X_test, y_test, label_encoder

##### Load Dataset

X_train, y_train, X_test, y_test, label_encoder = load_dataset(
    'train.csv',
    'test.csv'
)

# Simpan LabelEncoder
joblib.dump(label_encoder, "label_encoder.pkl")

print("Label encoder berhasil dibuat dan disimpan.")
print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

num_classes = len(label_encoder.classes_)

print("Jumlah kelas:", num_classes)
print("Daftar kelas:", label_encoder.classes_)

# --- Multilayer Perceptron Model ---
def create_mlp_model(input_dim, num_classes):
    model = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(input_dim,)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.25),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

# --- Callback MLP ---
mlp_callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=10,
        restore_best_weights=True,
        verbose=1
    ),

    tf.keras.callbacks.ModelCheckpoint(
        filepath=os.path.join(checkpoint_dir, 'best_model_mlp.h5'),
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),

    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=5,
        min_lr=1e-6,
        verbose=1
    ),

    tf.keras.callbacks.TensorBoard(
        log_dir='./logs/mlp'
    )
]

# --- Training MLP ---
mlp_model = create_mlp_model(input_dim, num_classes)

print("\nTraining Multilayer Perceptron (MLP)...")

mlp_history = mlp_model.fit(
    X_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(X_test, y_test),
    callbacks=mlp_callbacks,
    verbose=1
)

"""## Evaluation and Visualization"""

print("\nEvaluating MLP Model:")

# Evaluasi model MLP
mlp_loss, mlp_acc = mlp_model.evaluate(X_test, y_test)

# Ambil akurasi training terakhir
mlp_train_acc = mlp_history.history['accuracy'][-1]

print(f"Train Accuracy (MLP): {mlp_train_acc:.4f}")
print(f"Test Accuracy (MLP): {mlp_acc:.4f}")

# Classification Report
y_pred_mlp = mlp_model.predict(X_test).argmax(axis=1)

print("\nClassification Report (MLP):")
print(classification_report(
    y_test,
    y_pred_mlp,
    target_names=label_encoder.classes_
))

# --- Confusion Matrix (MLP) ---
cm_mlp = confusion_matrix(y_test, y_pred_mlp)

plt.figure(figsize=(8, 6))
sns.heatmap(
    cm_mlp,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=label_encoder.classes_,
    yticklabels=label_encoder.classes_
)

plt.title('Confusion Matrix - MLP')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()

# --- Plot Akurasi dan Loss MLP ---
acc = mlp_history.history['accuracy']
val_acc = mlp_history.history['val_accuracy']
loss = mlp_history.history['loss']
val_loss = mlp_history.history['val_loss']

epochs_range = range(len(acc))

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, 'r', label='Train Acc')
plt.plot(epochs_range, val_acc, 'b', label='Val Acc')
plt.title('MLP: Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, 'r', label='Train Loss')
plt.plot(epochs_range, val_loss, 'b', label='Val Loss')
plt.title('MLP: Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.show()

"""## Model Conversion

### SavedModel (TensorFlow)
"""

mlp_model.export(saved_model_mlp_dir)

shutil.make_archive('saved_models_mlp', 'zip', 'saved_models_mlp')
from google.colab import files
files.download('saved_models_mlp.zip')

"""### TensorFlow.js (TFJS)"""

!tensorflowjs_converter \
    --input_format=tf_saved_model \
    /content/saved_models_mlp/ \
    /content/mlp_tfjs_model

shutil.make_archive('mlp_tfjs_model', 'zip', 'mlp_tfjs_model')
files.download('mlp_tfjs_model.zip')

!pip freeze > requirements.txt