# -*- coding: utf-8 -*-
"""Training BISINDO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DXL1_tWHiTSrlBTgJEh4FxjkLMqRMkYQ

# Machine Learning Project by Rizka Alfadilla: [BISINDO0]

## Packages/Library
"""

# Tunggu hingga semua library terinstall baru restart session

!pip install tensorflowjs

# Menonaktifkan warning yang mungkin muncul
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Library Umum
import os
import sys
import shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

# Machine Learning & Model Inference
import tensorflow as tf
import joblib
import tensorflowjs

# Pelatihan dan evaluasi
import seaborn as sns
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Mencetak versi Library yang sedang digunakan
print(f'Python Version: {sys.version.split()[0]}')
print(f'Pandas Version: {pd.__version__}')
print(f'Numpy Version: {np.__version__}')
print(f'Scikit Learn Version: {sklearn.__version__}')
print(f'Tensorflow Version: {tf.__version__}')
print(f'TensorFlow.js Version: {tensorflowjs.__version__}')

"""## Data Preparation

### Data Loading
"""

df = pd.read_csv("bisindo_landmarks_scaled.csv")

df.head(10)

# Plot distribusi gambar di setiap kelas
Label = df['label']
plt.figure(figsize = (6,6))
sns.set_style("darkgrid")
plot_data = sns.countplot(Label)

df['label'].value_counts()

"""### Data Preprocessing

#### Split Dataset
"""

def split_train_val_test(
    csv_filename,
    train_file,
    val_file,
    test_file,
    train_size=0.70,
    val_size=0.15,
    test_size=0.15,
    random_state=42
):
    # Pastikan total proporsi sama dengan 1
    total_size = train_size + val_size + test_size

    if not abs(total_size - 1.0) < 1e-9:
        raise ValueError(
            "Jumlah train_size, val_size, dan test_size harus sama dengan 1."
        )

    # Memuat dataset
    df = pd.read_csv(csv_filename)

    # Memastikan kolom label tersedia
    if "label" not in df.columns:
        raise ValueError("CSV harus memiliki kolom 'label'.")

    # Memisahkan fitur dan label
    X = df.drop(columns=["label"])
    y = df["label"]

    # Tahap 1:
    # Membagi 70% data pelatihan dan 30% data sementara
    X_train, X_temp, y_train, y_temp = train_test_split(
        X,
        y,
        train_size=train_size,
        stratify=y,
        random_state=random_state,
        shuffle=True
    )

    # Menghitung proporsi test terhadap data sementara
    relative_test_size = test_size / (val_size + test_size)

    # Tahap 2:
    # Membagi data sementara menjadi 15% validasi dan 15% pengujian
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp,
        y_temp,
        test_size=relative_test_size,
        stratify=y_temp,
        random_state=random_state,
        shuffle=True
    )

    # Menggabungkan kembali label dan fitur
    train_df = pd.concat(
        [
            y_train.reset_index(drop=True),
            X_train.reset_index(drop=True)
        ],
        axis=1
    )

    val_df = pd.concat(
        [
            y_val.reset_index(drop=True),
            X_val.reset_index(drop=True)
        ],
        axis=1
    )

    test_df = pd.concat(
        [
            y_test.reset_index(drop=True),
            X_test.reset_index(drop=True)
        ],
        axis=1
    )

    # Menyimpan masing-masing subset ke file CSV
    train_df.to_csv(train_file, index=False)
    val_df.to_csv(val_file, index=False)
    test_df.to_csv(test_file, index=False)

    # Menampilkan hasil pembagian
    print("Dataset berhasil dibagi:")
    print(
        f"  Train Set      : {train_df.shape[0]} sampel, "
        f"{train_df.shape[1]} kolom"
    )
    print(
        f"  Validation Set : {val_df.shape[0]} sampel, "
        f"{val_df.shape[1]} kolom"
    )
    print(
        f"  Test Set       : {test_df.shape[0]} sampel, "
        f"{test_df.shape[1]} kolom"
    )

    print("\nPersentase aktual:")
    print(f"  Train      : {len(train_df) / len(df) * 100:.2f}%")
    print(f"  Validation : {len(val_df) / len(df) * 100:.2f}%")
    print(f"  Test       : {len(test_df) / len(df) * 100:.2f}%")

    return train_df, val_df, test_df

train_df, val_df, test_df = split_train_val_test(
    csv_filename="bisindo_landmarks_scaled.csv",
    train_file="train.csv",
    val_file="validation.csv",
    test_file="test.csv"
)

"""## Modelling"""

# Parameter
epochs = 100
batch_size = 32

checkpoint_dir = "./checkpoints"
saved_model_mlp_dir = "./saved_models_mlp"

# Pastikan folder tersedia
os.makedirs(checkpoint_dir, exist_ok=True)
os.makedirs(saved_model_mlp_dir, exist_ok=True)


##### Function: Load Train, Validation, and Test Dataset

def load_dataset(train_file, val_file, test_file):
    # Membaca masing-masing subset
    train_df = pd.read_csv(train_file)
    val_df = pd.read_csv(val_file)
    test_df = pd.read_csv(test_file)

    # Memastikan seluruh file memiliki kolom label
    for file_name, dataframe in {
        "train": train_df,
        "validation": val_df,
        "test": test_df
    }.items():
        if "label" not in dataframe.columns:
            raise ValueError(
                f"File {file_name} harus memiliki kolom 'label'."
            )

    # Kolom yang tidak digunakan sebagai fitur model
    non_feature_columns = ["label", "path", "file_name"]

    def separate_features_and_labels(dataframe):
        drop_columns = [
            column
            for column in non_feature_columns
            if column in dataframe.columns
        ]

        X = dataframe.drop(columns=drop_columns).values.astype("float32")
        y = dataframe["label"].values

        return X, y

    # Memisahkan fitur dan label
    X_train, y_train = separate_features_and_labels(train_df)
    X_val, y_val = separate_features_and_labels(val_df)
    X_test, y_test = separate_features_and_labels(test_df)

    # Memastikan jumlah fitur konsisten
    if not (
        X_train.shape[1]
        == X_val.shape[1]
        == X_test.shape[1]
    ):
        raise ValueError(
            "Jumlah fitur pada train, validation, dan test tidak sama."
        )

    # LabelEncoder hanya di-fit menggunakan data pelatihan
    label_encoder = LabelEncoder()
    y_train = label_encoder.fit_transform(y_train)

    # Memastikan tidak terdapat label baru pada validation dan test
    train_classes = set(label_encoder.classes_)

    unknown_val_labels = set(y_val) - train_classes
    unknown_test_labels = set(y_test) - train_classes

    if unknown_val_labels:
        raise ValueError(
            f"Label pada validation tidak ditemukan di train: "
            f"{unknown_val_labels}"
        )

    if unknown_test_labels:
        raise ValueError(
            f"Label pada test tidak ditemukan di train: "
            f"{unknown_test_labels}"
        )

    # Transformasi label validation dan test
    y_val = label_encoder.transform(y_val)
    y_test = label_encoder.transform(y_test)

    return (
        X_train,
        y_train,
        X_val,
        y_val,
        X_test,
        y_test,
        label_encoder
    )


##### Load Dataset

(
    X_train,
    y_train,
    X_val,
    y_val,
    X_test,
    y_test,
    label_encoder
) = load_dataset(
    train_file="train.csv",
    val_file="validation.csv",
    test_file="test.csv"
)

# Simpan LabelEncoder
joblib.dump(label_encoder, "label_encoder.pkl")

print("Label encoder berhasil dibuat dan disimpan.")

print("\nUkuran fitur:")
print("X_train shape:", X_train.shape)
print("X_val shape  :", X_val.shape)
print("X_test shape :", X_test.shape)

print("\nUkuran label:")
print("y_train shape:", y_train.shape)
print("y_val shape  :", y_val.shape)
print("y_test shape :", y_test.shape)

# Jumlah fitur dan kelas ditentukan dari dataset
input_dim = X_train.shape[1]
num_classes = len(label_encoder.classes_)

print("\nJumlah fitur:", input_dim)
print("Jumlah kelas:", num_classes)
print("Daftar kelas:", label_encoder.classes_)

# Validasi jumlah fitur landmark
expected_input_dim = 126

if input_dim != expected_input_dim:
    raise ValueError(
        f"Jumlah fitur ditemukan {input_dim}, "
        f"sedangkan yang diharapkan {expected_input_dim}."
    )

# --- Multilayer Perceptron Model ---
def create_mlp_model(input_dim, num_classes):
    model = tf.keras.models.Sequential(
        [
            tf.keras.layers.Input(
                shape=(input_dim,),
                name="input_landmark"
            ),

            tf.keras.layers.Dense(
                128,
                activation="relu",
                name="hidden_layer_1"
            ),

            tf.keras.layers.Dropout(
                0.25,
                name="dropout_1"
            ),

            tf.keras.layers.Dense(
                64,
                activation="relu",
                name="hidden_layer_2"
            ),

            tf.keras.layers.Dropout(
                0.20,
                name="dropout_2"
            ),

            tf.keras.layers.Dense(
                num_classes,
                activation="softmax",
                name="output_layer"
            )
        ],
        name="MLP_BISINDO"
    )

    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate=0.001
        ),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

# --- Callback MLP ---
mlp_callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        mode="min",
        patience=10,
        restore_best_weights=True,
        verbose=1
    ),

    tf.keras.callbacks.ModelCheckpoint(
        filepath=os.path.join(
            checkpoint_dir,
            "best_model_mlp.h5"
        ),
        monitor="val_loss",
        mode="min",
        save_best_only=True,
        verbose=1
    ),

    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        mode="min",
        factor=0.5,
        patience=5,
        min_lr=1e-6,
        verbose=1
    ),

    tf.keras.callbacks.TensorBoard(
        log_dir="./logs/mlp"
    )
]

# --- Training MLP ---
mlp_model = create_mlp_model(
    input_dim=input_dim,
    num_classes=num_classes
)

print("\nTraining Multilayer Perceptron (MLP)...")

mlp_history = mlp_model.fit(
    X_train,
    y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_data=(X_val, y_val),
    callbacks=mlp_callbacks,
    verbose=1,
    shuffle=True
)

"""## Evaluation and Visualization"""

print("\nEvaluating MLP Model:")

# Memuat model terbaik hasil ModelCheckpoint
best_model_path = os.path.join(
    checkpoint_dir,
    "best_model_mlp.h5"
)

best_mlp_model = tf.keras.models.load_model(
    best_model_path
)

# Evaluasi pada data training
mlp_train_loss, mlp_train_acc = best_mlp_model.evaluate(
    X_train,
    y_train,
    verbose=0
)

# Evaluasi pada data validation
mlp_val_loss, mlp_val_acc = best_mlp_model.evaluate(
    X_val,
    y_val,
    verbose=0
)

# Evaluasi akhir pada data testing
mlp_test_loss, mlp_test_acc = best_mlp_model.evaluate(
    X_test,
    y_test,
    verbose=0
)

print(f"Train Loss       : {mlp_train_loss:.4f}")
print(f"Train Accuracy   : {mlp_train_acc:.4f}")

print(f"Validation Loss  : {mlp_val_loss:.4f}")
print(f"Validation Acc.  : {mlp_val_acc:.4f}")

print(f"Test Loss        : {mlp_test_loss:.4f}")
print(f"Test Accuracy    : {mlp_test_acc:.4f}")


# Prediksi pada data pengujian
y_pred_probability = best_mlp_model.predict(
    X_test,
    verbose=0
)

y_pred_mlp = np.argmax(
    y_pred_probability,
    axis=1
)


# Classification Report
print("\nClassification Report (MLP):")

print(
    classification_report(
        y_test,
        y_pred_mlp,
        target_names=label_encoder.classes_,
        digits=4,
        zero_division=0
    )
)

# --- Confusion Matrix (MLP) ---
cm_mlp = confusion_matrix(
    y_test,
    y_pred_mlp
)

plt.figure(figsize=(8, 6))

sns.heatmap(
    cm_mlp,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=label_encoder.classes_,
    yticklabels=label_encoder.classes_,
    annot_kws={"size": 8}
)

plt.title("Confusion Matrix Model MLP")
plt.xlabel("Kelas Prediksi")
plt.ylabel("Kelas Aktual")

plt.xticks(rotation=0)
plt.yticks(rotation=0)

plt.tight_layout()

# Menyimpan gambar untuk dokumentasi skripsi
plt.savefig(
    "confusion_matrix_mlp.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# --- Plot Akurasi dan Loss MLP ---

acc = mlp_history.history["accuracy"]
val_acc = mlp_history.history["val_accuracy"]
loss = mlp_history.history["loss"]
val_loss = mlp_history.history["val_loss"]

# Nomor epoch dimulai dari 1
epochs_range = range(1, len(acc) + 1)

plt.figure(figsize=(12, 5))

# Grafik akurasi
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label="Training Accuracy")
plt.plot(epochs_range, val_acc, label="Validation Accuracy")
plt.title("Training and Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(alpha=0.3)

# Grafik loss
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label="Training Loss")
plt.plot(epochs_range, val_loss, label="Validation Loss")
plt.title("Training and Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(alpha=0.3)

plt.tight_layout()

plt.savefig(
    "training_validation_mlp.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

"""## Model Conversion

### SavedModel (TensorFlow)
"""

# --- Export Model Terbaik ke SavedModel ---
best_mlp_model.export(saved_model_mlp_dir)

print(
    f"Model terbaik berhasil diekspor ke: "
    f"{saved_model_mlp_dir}"
)

# --- Kompres SavedModel menjadi ZIP ---
zip_path = shutil.make_archive(
    base_name="best_model_mlp_savedmodel",
    format="zip",
    root_dir=saved_model_mlp_dir
)

print("File ZIP berhasil dibuat:", zip_path)

# --- Download file ZIP dari Google Colab ---
from google.colab import files

files.download(zip_path)

"""### TensorFlow.js (TFJS)"""

!tensorflowjs_converter \
    --input_format=tf_saved_model \
    /content/saved_models_mlp/ \
    /content/mlp_tfjs_model

# --- Kompres model TensorFlow.js menjadi ZIP ---
zip_path = shutil.make_archive(
    base_name="mlp_tfjs_model",
    format="zip",
    root_dir=".",
    base_dir="mlp_tfjs_model"
)

print("File ZIP berhasil dibuat:", zip_path)

# Mengunduh file ZIP
files.download(zip_path)

!pip freeze > requirements.txt